name: Release Flomo UI (macOS)
on:
  push:
    tags:
      - 'flomo-ui-v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract version from tag
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/flomo-ui-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0-dev" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install frontend dependencies
        working-directory: ./flomo-ui
        run: pnpm install

      - name: Build for Apple Silicon
        id: build-silicon
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Flomo Garden v${{ steps.get_version.outputs.VERSION }}'
          releaseBody: |
            ## 下载说明
            
            - **Apple Silicon (M1/M2/M3)**: 下载 `aarch64.dmg` 文件
            - **Intel Mac**: 下载 `x86_64.dmg` 文件
            
            ## 安装说明
            
            由于使用了临时签名，首次打开应用时可能需要：
            1. 右键点击应用，选择"打开"
            2. 在弹出的对话框中再次点击"打开"
            3. 或在"系统偏好设置 > 隐私与安全性"中允许应用运行
            
            ## 更新日志
            
            [在此添加更新内容]
          releaseDraft: true
          prerelease: false
          args: --target aarch64-apple-darwin
          projectPath: ./flomo-ui
          
      - name: Build for Intel Mac
        id: build-intel
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Flomo Garden v${{ steps.get_version.outputs.VERSION }}'
          releaseBody: 'See release notes above'
          releaseDraft: true
          prerelease: false
          args: --target x86_64-apple-darwin
          projectPath: ./flomo-ui
          releaseId: ${{ steps.build-silicon.outputs.releaseId }}
          
      - name: Add installation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a simple installation script
          cat > install-flomo-garden.sh << 'EOF'
          #!/bin/bash
          # Flomo Garden Installation Script
          
          echo "Flomo Garden 安装脚本"
          echo "===================="
          
          # Detect architecture
          ARCH=$(uname -m)
          if [ "$ARCH" = "arm64" ]; then
              DMG_SUFFIX="aarch64"
              echo "检测到 Apple Silicon Mac"
          else
              DMG_SUFFIX="x86_64"
              echo "检测到 Intel Mac"
          fi
          
          # Download URL (will be updated with actual release URL)
          VERSION="${1:-latest}"
          DOWNLOAD_URL="https://github.com/YOUR_USERNAME/YOUR_REPO/releases/download/flomo-ui-v${VERSION}/flomo-garden_${VERSION}_${DMG_SUFFIX}.dmg"
          
          echo "下载中..."
          curl -L -o flomo-garden.dmg "$DOWNLOAD_URL"
          
          echo "挂载 DMG..."
          hdiutil attach flomo-garden.dmg
          
          echo "复制到应用程序..."
          cp -R "/Volumes/Flomo Garden/Flomo Garden.app" /Applications/
          
          echo "卸载 DMG..."
          hdiutil detach "/Volumes/Flomo Garden"
          
          echo "清理..."
          rm flomo-garden.dmg
          
          echo "安装完成！"
          echo "首次运行请右键点击应用选择'打开'"
          EOF
          
          # Upload the script (this is just for reference, actual upload would need the release ID)
          echo "Installation script created"